# Generated by Django 4.2.3 on 2023-10-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
